spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zunfa?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver #如果mysql驱动6.0以上《com.mysql.jdbc.Driver》需要加cj 一下《com.mysql.jdbc.Driver》
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    properties:
      hibernate:
       ddl-auto: update
       naming:
         physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

    show-sql: true